import { SessionProvider } from "next-auth/react";
import Head from "next/head";
import { GlobalStyles } from "../src/styles/Global";
import { theme } from "../src/styles/themes/MainThemes";
import { ThemeProvider } from "styled-components";
import "../src/styles/Globalstyles.css";
import { Navbar } from "../components/Navbar";
import StyledMain from "../components/StyledMain";
import Footer from "../components/Footer";
import Auth from "../components/auth";
import { useState } from "react";

const App = ({ Component, pageProps }: any) => {
  const [searchTerm, setSearchTerm] = useState<string>();

  return (
    <>
      <Head>
        <title>Strings Online</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <SessionProvider session={pageProps.session}>
        <ThemeProvider theme={theme}>
          <GlobalStyles />
          <Navbar />
          {Component.auth ? (
            <Auth>
              <StyledMain>
                <Component {...pageProps} />
              </StyledMain>
            </Auth>
          ) : (
            <StyledMain>
              <Component {...pageProps} />
            </StyledMain>
          )}
          <Footer />
        </ThemeProvider>
      </SessionProvider>
    </>
  );
};
export default App;
