import type { AppProps } from "next/app";
import Head from "next/head";
import { GlobalStyles } from "../src/styles/Global";
import { theme } from "../src/styles/themes/MainThemes";
import { ThemeProvider } from "styled-components";
import "../src/styles/Globalstyles.css";

const App = ({ Component, pageProps }: AppProps) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <ThemeProvider theme={theme}>
        <GlobalStyles />
        <Component {...pageProps} />
      </ThemeProvider>
    </>
  );
};
export default App;
